services:
  dbcsv-server:
    image: dbcsv-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  dbcsv-client:
    image: dbcsv-client
    build:
      context: ./client
      dockerfile: Dockerfile
