version: "3.8"

services:
  web:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8001'
    volumes:
      - .:/app # Updated volume mount
    ports:
      - 8001:8001
